  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  joint_head_controller:
    type: effort_controllers/JointPositionController
    joint: head_joint
    pid: {p: 0.5, i: 0.1, d: 0.2}
